/* Additional record code for Annex60.Controls.Continuous.Examples.LimPID generated by the OpenModelica Compiler OpenModelica 1.12.0~dev-411-ge18c6dd. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

